import Head from "next/head";
import type { Post } from "../../modules/post/types/post";

type PostParams = {
    id: string;
};

export default function PostPage({ post }: { post: Post }) {
    return (
        <>
            <Head>
                <title>RemplaMed | {post.id}</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="text-lg font-bold uppercase">{post.author}</div>
            <div>{post.content}</div>
        </>
    );
}

export function getStaticPaths() {
    return {
        paths: [
            // can get paths from database
            { params: { id: "1A" } },
            { params: { id: "2B" } },
            { params: { id: "3C" } },
        ],
        fallback: false,
    };
}

export function getStaticProps({ params }: { params: PostParams }) {
    const post: Post = {
        id: params.id,
        author: "John Doe",
        content:
            "I am the content of the post.\n Here is my phone number: 0612345678. This is from the dynamic route.",
    };
    return {
        props: {
            post,
        },
    };
}
