import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import PrivatePost from "../components/post/privatePost";
import Header from "../components/layout/header";

const mockPost = {
  id: "1A",
  author: "John Doe",
  content: "I am the content of the post.\n Here is my phone number: 0612345678",
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>RemplaMed</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className="p-4">
        <Link href={`/posts/${mockPost.id}`}>
          <PrivatePost key={1} post={mockPost}/>
        </Link>
      </main>
    </>
  );
};

export default Home;
